services:
  # =======================================
  # COORDINADOR DE CITUS
  # =======================================
  citus_coordinator:
    image: citusdata/citus:12.1
    container_name: citus_coordinator
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=citusdb
    ports:
      - "5432:5432"
    networks:
      - citus_net
    volumes:
      - citus_coordinator_data:/var/lib/postgresql/data

  # =======================================
  # NODOS WORKER DE CITUS
  # =======================================
  citus_worker1:
    image: citusdata/citus:12.1
    container_name: citus_worker1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - citus_coordinator
    networks:
      - citus_net

  citus_worker2:
    image: citusdata/citus:12.1
    container_name: citus_worker2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - citus_coordinator
    networks:
      - citus_net

  citus_worker3:
    image: citusdata/citus:12.1
    container_name: citus_worker3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - citus_coordinator
    networks:
      - citus_net

  # =======================================
  # BACKEND FLASK
  # =======================================
  backend:
    build: ./backend
    container_name: flask_backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - CITUS_HOST=citus_coordinator
      - CITUS_PORT=5432
      - CITUS_DB=citusdb
      - CITUS_USER=postgres
      - CITUS_PASSWORD=postgres
    volumes:
      - ./backend:/app
    depends_on:
      - citus_coordinator
    networks:
      - citus_net

  # =======================================
  # FRONTEND REACT
  # =======================================
  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "5173:5173"
    working_dir: /app
    command: ["npm", "run", "dev"]
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - citus_net

  # =======================================
  # PGADMIN PARA CITUS
  # =======================================
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@local.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - citus_coordinator
    networks:
      - citus_net
    volumes:
      - pgadmin_data:/var/lib/pgadmin

# =======================================
# RED Y VOLUMENES
# =======================================
networks:
  citus_net:
    driver: bridge

volumes:
  citus_coordinator_data:
  pgadmin_data:
# =======================================
# NOTAS:
# - Levantar todo: docker-compose up --build
# - Levantar solo backend: docker-compose up --build backend
# - Levantar solo frontend: docker-compose up --build frontend
# - Acceder a pgAdmin: http://localhost:5050 (usuario: admin@ local.com, pass: admin)
# - Conectarse al coordinador en pgAdmin:
#   Host: citus_coordinator
#   Puerto: 5432
#   Usuario: postgres
#   Pass: postgres
#   DB: citusdb
# =======================================
# - Acceder al backend: http://localhost:5000
# - Acceder al frontend: http://localhost:5173
# =======================================

